dependencies :
  - commerce_cart
  - commerce_product_reference
variables :
  cardinality :
    type : numeric
    placeholder : 1
    required : false
    default : 1
    description: Number of values that would be held in the field