version: '2'
services:
  web:
    image: factorial/drupal-docker:php-56
    volumes:
      - .:/var/www:cached
    links:
      - mysql:mysql
      - solr:solr
    environment:
      VHOST: $VHOST
      WEB_ROOT: $WEB_ROOT
    network_mode: bridge

  mysql:
    image: mysql:5
    volumes:
      - "db-data:/var/lib/mysql"

    environment:
      MYSQL_ROOT_PASSWORD: "admin"
    network_mode: bridge

  solr:
    image: solr:5
    network_mode: bridge
    volumes:
      - "./sites/all/modules/contrib/apachesolr/solr-conf/solr-5.x:/myconfig/conf"
    entrypoint:
        - docker-entrypoint.sh
        - solr-precreate
        - mycore
        - /myconfig
volumes:
  db-data:
