site_name: Entity Scaffolder
theme: readthedocs
markdown_extensions:
  - admonition

repo_url: https://github.com/factorial-io/entity_scaffolder
repo_name: GitHub
# edit_uri: edit/develop/docs/docs/
site_description: Entity Scaffolder Documentation
site_author: Factorial GmbH, Hamburg
copyright: © 2018 Factorial GmbH, Hamburg

pages:
  - index.md
  - available-tasks.md
  - Configurations:
      - config.yaml: configurations/config.md
  - Fieldable entities:
      - Entities: configurations/entities.md
      - Fields: configurations/fields.md
  - Features: configurations/text_filters.md
  - Pictures:
      - Breakpoint Groups: configurations/breakpoint_groups.md
      - Image styles: configurations/image_styles.md
      - Pictures: configurations/pictures.md

  - Contribution Guide:
      - EntityScaffolder: contribute/entity-scaffolder.md
      - Documentation: contribute/documentation.md
extra_css:
  - css/version-select.css
extra_javascript:
  - js/version-select.js
