site_name: Entity Scaffolder
theme: readthedocs
markdown_extensions:
  - admonition

repo_url: https://github.com/factorial-io/entity_scaffolder
repo_name: GitHub
# edit_uri: edit/develop/docs/docs/
site_description: Entity Scaffolder Documentation
site_author: Factorial GmbH, Hamburg
copyright: © 2018 Factorial GmbH, Hamburg

pages:
  - index.md
  - Contribution Guide:
      - EntityScaffolder: contribute/entity-scaffolder.md
      - Documentation: contribute/documentation.md
extra_css:
  - css/version-select.css
extra_javascript:
  - js/version-select.js
