name : Deploy Module
interactive: true
files:
 '/factory7_deploy.info' : '/{{ module_deploy_machine_name }}.info'
 '/factory7_deploy.install' : '/{{ module_deploy_machine_name }}.install'
 '/factory7_deploy.module' : '/{{ module_deploy_machine_name }}.module'
variables :
  module_deploy_machine_name :
    label : Deploy Module Machine name
    required : true
    default : ''
    pattern : '{{ project_short_code }}_deploy'
    hidden : true
  directory :
    label : Path to root
    required : true
    default : ''
    pattern : 'sites/all/modules/custom/{{ module_deploy_machine_name }}'
    hidden : true
  