name : Entity Scaffolder Configuration
interactive: true
variables :
  directory :
    label : Path to Entity Scaoffolder config directory
    required : true
    default : '.tools/es'
    hidden : true
  directories_theme :
    label : Path to theme folder (without terminating slash "/")
    required : true
    default : ''
    pattern : 'sites/all/themes/custom/{{ project_short_code }}_frontend'
    hidden : true
  directories_templates :
    label : Path to templates folder (relative to theme)
    required : true
    default : 'templates'
    pattern : '{{ directories_theme }}/{{ directories_templates }}'
    hidden : true
  directories_patternlab :
    label : Path to patternlab (relative to theme)
    required : true
    default : 'source'
    pattern : '{{ directories_theme }}/{{ directories_patternlab }}'
    hidden : true
