commands:
  init:
    - config
    - theme
    - module_deploy
  init-bi:
    - fabalicious_bi_d7
    - config
    - theme
    - module_deploy
    - module_utils
interactive : true
variables :
  version :
    label : Version of Entity Scaffolder to use
    required : true
    default : 'd7_1'
    hidden : true
  project_short_code :
    label : Project short code. Used for various prefixes like module names, theme names, etc. Suggested to use 2 or 3 alphabets.
    required : true
    default : ''
