name : Utils Module
interactive: true
files:
 '/factory7_utils.info' : '/{{ module_utils_machine_name }}.info'
 '/factory7_utils.install' : '/{{ module_utils_machine_name }}.install'
 '/factory7_utils.module' : '/{{ module_utils_machine_name }}.module'
variables :
  module_utils_machine_name :
    label : Deploy Module Machine name
    required : true
    default : ''
    pattern : '{{ project_short_code }}_utils'
    hidden : true
  directory :
    label : Path to root
    required : true
    default : ''
    pattern : 'sites/all/modules/custom/{{ module_utils_machine_name }}'
    hidden : true
