site_name: Entity Scaffolder
theme: readthedocs
markdown_extensions:
  - admonition

repo_url: https://source.factorial.io/skakanat/entity_scaffolder
repo_name: GitLab
edit_uri: edit/develop/docs/docs/
site_description: "Entity Scaffolder Documentation"
site_author: "Factorial GmbH, Hamburg"
copyright: "© 2017 Factorial GmbH, Hamburg"

pages:
- index.md
- installation.md
- usage.md
- available-tasks.md
- configuration.md
- contribute.md
