name : Fabalicious
interactive: true
variables :
  directory :
    label : Path to root
    required : true
    default : '.'
    hidden : true
  project_short_name :
    label : Short name of the project. This will be used to create url, project folder names and so on.
    required : true
    default : ''
  project_bi_code :
    label : BI Project Code
    required : true
    default : ''
  project_port_web :
    label : Port number - WEB
    required : true
    default : ''
    hidden : true
    pattern : '{{ random(55535) + 10000 }}'
  project_port_solr :
    label : Port number - SOLR
    requierd : true
    default : ''
    hidden : true
    pattern : '{{ random(55535) + 10000 }}'
    